### ISSUE TITLE
RLV Release

### ISSUE THREAD

**Issue by SweetStephy** [nPoseTeam/nPose-RLV-Plugin#1]
I don't know if this is the right place. Is there a way to get the RLV release event to trigger a LINKMSG to the chains script to release the chains? It would be a simple matter if there were BTN notecards for the RLV+ Menu. The stand button becoming available is not always obvious to the captive.

A world text script for the time remaining would also be very helpful.

if I knew how to script I would do it myself and contribute it here, but I don't.

**Comment by LeonaMorro** [comment]
Hi SweetStephy,

> I don't know if this is the right place 

It is ;)

>  Is there a way to get the RLV release event to trigger a LINKMSG to the chains script to release the chains?

Currently not. Unfortunately the timer event in the RLV+ core also don't use a linkmessage, but releases a victim on the fly. I will change this. After the change you should be able to listen to the linkmessages from/to the RLV+ core and translate a "release message" into a "unchain message"

> A world text script for the time remaining would also be very helpful.
> Do you mean Floating Text (llSetText)?

**Comment by LeonaMorro** [comment]
I added a patch to the master branch, please try the updated [RLV+ Core](https://raw.githubusercontent.com/LeonaMorro/nPose-RLV-Plugin/master/LSLScripts/nPose%20RLV%2B%20Core.lsl).

You now should be able to listen to the `RLV_CORE_COMMAND` `release` link message (see https://github.com/LeonaMorro/nPose-RLV-Plugin/wiki/Link-messages) and do what ever you want in your own script.
Please ask me If you need an example.

**Comment by SweetStephy** [comment]
Please, I'd love an example. I can sometimes modify scripts to do what I want if I can recognize enough from names and context, but I certainly can't write my own. I ended up having to do that to set the 2default option to "on" in the nPose Menu script. And as far as I can tell, that is the only way to be able to set any other options reliably, including the options for RLV+.

And yes, I meant floating text, like other traps have as an option for status and timers.

**Comment by LeonaMorro** [comment]
Example script (untested)(for use with the updated core)

``` LSL
//RLV+
//https://github.com/LeonaMorro/nPose-RLV-Plugin/wiki/Link-messages
integer RLV_CORE_COMMAND=-8010;
string RLV_CORE_RELEASE="release";

//nPose LM/LG chains plugin
//https://github.com/LeonaMorro/nPose-LM-LG-chains-plugin
integer gCMD_REM_CHAINS=2733; //remove chains
string CHAIN_POINTS="test1~test2"; //specify the chainpoints



default {
    link_message(integer sender_num, integer num, string str, key id) {
        if(num==RLV_CORE_COMMAND) {
            list temp=llParseStringKeepNulls(str,[","], []);
            string cmd=llToLower(llStringTrim(llList2String(temp, 0), STRING_TRIM));
            if(cmd==RLV_CORE_RELEASE) {
                key target=(key)llStringTrim(llList2String(temp, 1), STRING_TRIM);
                if(target) {
                    llMessageLinked(LINK_SET, gCMD_REM_CHAINS, CHAIN_POINTS, target);
                    llOwnerSay("Debug: removed chains (" + CHAIN_POINTS + ") from Avatar (" + (string)target + ").");
                }
            }
        }
    }
}
```

The problem with the floating text stuff is:
a) The RLV+ plugin can handle a unlimited (memory restricted) number of victims. Each victim can have a timer. So how to decide which timer should be shown in the floating text?
b) The floating text could be shown above any prim. Which prim should be used?

**Comment by SweetStephy** [comment]
Just to be sure I understand correctly. First I replace the RLV+ Core with the script you linked before. Then make a new script in the build with the contents you just posted, changing "test1~test2" to a tilde delimited list of the chain point names in my build. And that should work?

Sorry if I seem dense but I'm a total newbie to lsl. and not all that experienced with any sort of coding.

I hadn't considered the multiple captives with individual timers issue... I guess there is no good way around that.

**Comment by SweetStephy** [comment]
I must have understood correctly, because I tried doing that and it worked.... hehe thank you so much

**Comment by LeonaMorro** [comment]
Yes you have understood correctly. Nice to hear that it works :)
