### ISSUE TITLE
Possible bug, possibly not

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/nPose-RLV-Plugin#2]
[18:22] James (jameseekay): when clicking the -RLV- button
[18:22] James (jameseekay): it pops up but doesn't go further to any of the submenus
[18:22] James (jameseekay): I created a notecard SET:-RLV-
[18:22] James (jameseekay): this a content like this
[18:22] James (jameseekay): LINKMSG|-8000|showMenu,%AVKEY%,%CARDNAME%

**Comment by LeonaMorro** [comment]
Which nPose Version? Which RLV+ Version?
If it is nPose V3.00 and RLV+ V0.38, then it will not work. RLV+ V0.38 only works with nPose V2.00+.

I'm working on RLV+ V1.00 that runs with nPose V3.00. The test are already finished and I expect a release within the next week.

I also post this to jameseekay via IM.

**Comment by jameseekay** [comment]
I was using nPose V3.00 and the latest RLV+ that I downloaded from the github repo.  Here's the comment line from RLV+ Core and RLV+ Menu

// LSL script generated: LSLScripts.nPose RLV+ Core.lslp Tue May 17 17:06:12 Mitteleuropäische Sommerzeit 2016

// LSL script generated: LSLScripts.nPose RLV+ Core.lslp Tue May 17 17:06:12 Mitteleuropäische Sommerzeit 2016

**Comment by LeonaMorro** [comment]
Thats V0.38 for nPose 2

I merged the development branch into the master branch yesterday, so if you want to give it a new try, please download it again.
Please note that you have to change the RLV Notecard from `LINKMSG|-8000|showMenu,%AVKEY%,%CARDNAME%` to:

`PLUGINMENU|nPose_RLV+`

You can also get the scripts including a demo, inworld at our Headquarter ( http://maps.secondlife.com/secondlife/Oefelein/114/49/48 ) in a few days.

**Comment by jameseekay** [comment]
it works now! thanks
