### ISSUE TITLE
If owner is the victim, they can unsit in Admin menu

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/nPose-RLV-Plugin#5]
Owner can unsit in the Admin menu if they are in the victim's list.  I seems the button permission doesn't stop the owner when the notecard name is written like this:   SET:Utilities:Admin:Unsit{!victim}

**Comment by LeonaMorro** [comment]
The way UDPs are updated also changed with nPose V4. (You should use the DO linkmessage whenever possible). I guess the whole "victim" UDP isn't working anymore (regardless if the owner uses it or someone else). I'm going to look into it. I will also remove the [LSL Forge dependency](https://github.com/raysilent/lslforge)  and use  [Sei-Lisa 's LSL optimizer](https://github.com/Sei-Lisa/LSL-PyOptimizer) for the compressed version (like the prop plugin)

**Comment by LeonaMorro** [comment]
@HowardBaxton this has to be tested
